<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Moroz">

<title>Skeleton Document with Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="skeleton_repo_files/libs/clipboard/clipboard.min.js"></script>
<script src="skeleton_repo_files/libs/quarto-html/quarto.js"></script>
<script src="skeleton_repo_files/libs/quarto-html/popper.min.js"></script>
<script src="skeleton_repo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="skeleton_repo_files/libs/quarto-html/anchor.min.js"></script>
<link href="skeleton_repo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="skeleton_repo_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="skeleton_repo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="skeleton_repo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="skeleton_repo_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Skeleton Document with Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Moroz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="the-skeleton-repo" class="level2">
<h2 class="anchored" data-anchor-id="the-skeleton-repo">The Skeleton Repo</h2>
<section id="disclaimer" class="level4">
<h4 class="anchored" data-anchor-id="disclaimer">Disclaimer</h4>
<p>A repository and its corresponding R-project have been created to <strong>complete</strong> the ‘skeleton’ repository mini-project. Embedded within this R-project, I have decided to make my <em>own</em> questions that I will answer to demonstrate other relevant skills from the objective list. Making and answering these questions will allow me to make further commitments to the repository, allowing for clean and easy comprehension of my code.</p>
</section>
<section id="question-1" class="level4">
<h4 class="anchored" data-anchor-id="question-1">Question #1</h4>
<p>William is a student at the University of Chicago. William just finished taking three classes during the fall quarter, and needs help calculating and visualizing his GPA. The University of Chicago uses a standard A-grade conversion scale, where an ‘A’ equals a 4.00 GPA. William’s classes and grades are as follows:</p>
<p><strong>Causal Inference</strong>: A- <strong>Introduction to Python Programming</strong>: B <strong>From Data to Manuscript in R</strong>: B+</p>
<ol type="1">
<li>Make a data frame with William’s class, grade and quarter information.</li>
<li>Convert William’s letter grades to a numeric GPA using the standard A-grade conversion scale.</li>
<li>Add William’s letter grades as a column to the data frame.</li>
<li>Calculate William’s fall quarter GPA.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                               Class Quarter Letter Numeric
1                   Causal Inference    Fall     A-     3.7
2 Introduction to Python Programming    Fall      B     3.0
3       From Data to Manuscript in R    Fall     B+     3.3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.33</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="question-2" class="level4">
<h4 class="anchored" data-anchor-id="question-2">Question #2</h4>
<p>Write the newly created data frame to a csv.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Class, Quarter, Letter
dbl (1): Numeric

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Class                              Quarter Letter Numeric
  &lt;chr&gt;                              &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;
1 Causal Inference                   Fall    A-         3.7
2 Introduction to Python Programming Fall    B          3  
3 From Data to Manuscript in R       Fall    B+         3.3</code></pre>
</div>
</div>
</section>
<section id="question-3" class="level4">
<h4 class="anchored" data-anchor-id="question-3">Question #3</h4>
<p>Ten years after graduation, William is currently unhappy in his job as a bank manager due to his monetary compensation. William believes he can make more money as a lawyer, but is unsure whether he should apply to law school. Some of his friends, Jonathan, Martin, Olivia, Isabella, Daniel, and Paige, are lawyers and graduated from law school. Some of his other friends, Matthew, and Connor, never went to law school and are perfectly happy in their careers. Information about William and his friends are as follows:</p>
<ul>
<li>William had a 3.33 GPA, scored 167 on the LSAT, and participated in 2 extracurricular activities. He currently makes $63,002 as a bank manager.</li>
<li>Jonathan had a 3.95 GPA, scored 176 on the LSAT, and participated in 5 extracurricular activities. He currently makes $155,387 as a lawyer.</li>
<li>Martin had a 3.63 GPA, scored 170 on the LSAT, and participated in 2 extracurricular activities. He currently makes $122,098 as a lawyer.</li>
<li>Olivia had a 3.99 GPA, scored 179 on the LSAT, and participated in 0 extracurricular activities. She currently makes $113,000 as a lawyer.</li>
<li>Isabella had a 3.54 GPA, scored 168 on the LSAT, and participated in 3 extracurricular activities. She currently makes $105,000 as a lawyer.</li>
<li>Daniel had a 3.77 GPA, score 171 on the LSAT, and participated in 4 extracurricular activities. He currently makes $118,220 as a lawyer.</li>
<li>Paige had a 3.81 GPA, scored 175 on the LSAT, and participated in 2 extracurricular activities. She currently makes $94,562 as a lawyer.</li>
<li>Matthew had a 3.13 GPA, scored 154 on the LSAT, and participated in 3 extracurricular activities. He currently makes $76,000 as a supermarket manager.</li>
<li>Connor had a 3.31 GPA, scored 162 on the LSAT, and participated in 5 extracurricular activities. He currently makes $58,020 as a mortgage analyst.</li>
</ul>
<ol type="1">
<li>Make a data frame including each person’s name, GPA, LSAT, extracurricular activity participation, salary and law school status as columns.</li>
<li>Run a regression to determine whether there are any significant predictors of salary.</li>
<li>Plot your desired model and impose a line of best fit.</li>
<li>Write up the results of your regression analysis.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Salary ~ School, data = admissions_data)

Residuals:
   Min     1Q Median     3Q    Max 
-23482  -7654  -2672   4054  37342 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    65674      10534   6.234 0.000431 ***
School         52370      12902   4.059 0.004814 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18250 on 7 degrees of freedom
Multiple R-squared:  0.7018,    Adjusted R-squared:  0.6592 
F-statistic: 16.48 on 1 and 7 DF,  p-value: 0.004814</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  3.130   3.330   3.630   3.607   3.810   3.990 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  154.0   167.0   170.0   169.1   175.0   179.0 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   2.000   3.000   2.889   4.000   5.000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  58020   76000  105000  100588  118220  155387 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  1.0000  0.6667  1.0000  1.0000 </code></pre>
</div>
</div>
<p>Regression analyses were conducted on current and former University of Chicago students (n = 9) to investigate the effectiveness of predicting salary (<em>M</em> = 100,587, <em>SD</em> = 31,256) using measures of GPA (<em>M</em> = 3.61, <em>SD</em> = 0.30), LSAT score (<em>M</em> = 169.11, <em>SD</em> = 7.66), number of extracurricular activities (<em>M</em> = 2.89, <em>SD</em> = 1.62) and law school attendance (attended = 6, non-attended = 3). The model did not significantly account for variance of salary in the data, R<sup>2</sup> = .82, <em>F</em>(4, 4) = 4.46, p = .088. Since neither of GPA, LSAT score, number of extracurricular activities, or law school attendance accounted for significant variance in salary when all compiled in the model, additional analyses were tested measuring the efficacy of each individual predictor. When tested in a singular model, law school attendance accounted for 70% of the variance in salary in the data, R<sup>2</sup> = .70, <em>F</em>(1, 7) = 16.48, p &lt; .01.</p>
<p>The estimate of the coefficient for law school attendance was <em>b</em> = 52,370, <em>s<sub>b</sub></em> = 12,902, <em>t</em>(7) = 4.06, <em>p</em> = .004. This indicates that going to law school is associated with a $52,370 jump in salary as opposed to not having gone to law school. Based on data from this data set, our main hypothesis is supported in that William would greatly increase his earning potential by attending law school and becoming a lawyer.</p>
</section>
<section id="question-4" class="level4">
<h4 class="anchored" data-anchor-id="question-4">Question #4</h4>
<p>William has three other friends that are medical doctors. Their information are as follows:</p>
<ul>
<li>Tyrell had a 3.91 GPA, never took the LSAT, and participated in 5 extracurricular activities. He currently makes $388,267 as a cardiologist.</li>
<li>Savannah had a 3.85 GPA, never took the LSAT, and participated in 4 extracurricular activities. She currently makes $422,001 as an oncologist.</li>
<li>Gerald had a 3.89 GPA, never took the LSAT, and participated in 3 extracurricular activities. He currently makes $543,022 as a dermatologist.</li>
</ul>
<ol type="1">
<li>Add William’s doctor friends to the data frame.</li>
<li>Perform an ANOVA to determine whether there are differences in salary between lawyers, doctors, and non-lawyers or non-doctors.</li>
<li>Plot the results.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>            Df    Sum Sq   Mean Sq F value   Pr(&gt;F)    
School       1 2.228e+11 2.228e+11   29.84 0.000276 ***
Residuals   10 7.466e+10 7.466e+09                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    discard</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-5" class="level4">
<h4 class="anchored" data-anchor-id="question-5">Question #5</h4>
<p>Use a code chunk and R-Markdown to demonstrate in-line code, lists, and footnotes in Markdown.</p>
<p>My name is <strong>Michael</strong> and I have a dog named <em>Douglas</em>. Douglas just turned 5 and I adopted him 4 years ago. Douglas is originally from Phoenix, Arizona and he is the absolute best! Interestingly, Douglas is not the only one who is well-traveled. I have lived in Phoenix, Minneapolis and Edmonton<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> prior to moving to Chicago!</p>
</section>
<section id="question-6" class="level4">
<h4 class="anchored" data-anchor-id="question-6">Question #6</h4>
<p>Make a mathematical function that calculates GPA with any desired input.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "William had a 3.33 GPA during the Fall quarter"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Diana had a 3.67 GPA during the Winter quarter"</code></pre>
</div>
</div>
</section>
<section id="question-7" class="level4">
<h4 class="anchored" data-anchor-id="question-7">Question #7</h4>
<p>Practice your loop skills by using multiple loops in the same chunk of code.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Michael used to be 21 in 2023"
[1] "Michael used to be 20 in 2022"
[1] "Michael used to be 19 in 2021"
[1] "Michael used to be 18 in 2020"
[1] "Michael used to be 17 in 2019"
[1] "Michael used to be 16 in 2018"
[1] "Michael used to be 15 in 2017"
[1] "Michael used to be 14 in 2016"
[1] "Michael used to be 13 in 2015"
[1] "Michael used to be 12 in 2014"
[1] "Michael used to be 11 in 2013"
[1] "Michael used to be 10 in 2012"
[1] "Michael used to be 9 in 2011"
[1] "Michael used to be 8 in 2010"
[1] "Michael used to be 7 in 2009"
[1] "Michael used to be 6 in 2008"
[1] "Michael used to be 5 in 2007"
[1] "Michael used to be 4 in 2006"
[1] "Michael used to be 3 in 2005"
[1] "Michael used to be 2 in 2004"
[1] "Michael used to be 1 in 2003"
[1] "Michael was born in 2002"</code></pre>
</div>
</div>
</section>
<section id="question-8" class="level4">
<h4 class="anchored" data-anchor-id="question-8">Question #8</h4>
<p>Use dplyr and tidyr functions to modify the ‘admissions_data’ data set, then combine them together in one data transformation pipeline.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   Name     Salary   Age
   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
 1 William   63002    22
 2 Matthew   76000    23
 3 Connor    58020    25
 4 Isabella 105000    26
 5 Olivia   113000    26
 6 Daniel   118220    27
 7 Jonathan 155387    28
 8 Paige     94562    28
 9 Martin   122098    29
10 Gerald   543022    33
11 Tyrell   388267    35
12 Savannah 422001    37</code></pre>
</div>
</div>
</section>
<section id="question-9" class="level4">
<h4 class="anchored" data-anchor-id="question-9">Question #9</h4>
<p>Use ‘stringr’ functions to transform the data at your own discretion.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 7 7 6 8 6 6 8 5 6 6 6 8</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Name   Salary   Age
  &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 Will    63002    22
2 Matt    76000    23
3 Connor  58020    25
4 Bella  105000    26
5 Olivia 113000    26
6 Daniel 118220    27</code></pre>
</div>
</div>
</section>
<section id="question-10" class="level4">
<h4 class="anchored" data-anchor-id="question-10">Question #10</h4>
<p>Use two ‘forcats’ functions to transform the data at your own discretion.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Profession     n
  &lt;fct&gt;      &lt;int&gt;
1 Doctor         3
2 Lawyer         6
3 Non-DL         3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Non-DL Non-DL Non-DL Lawyer Lawyer Lawyer Lawyer Lawyer Lawyer Doctor
[11] Doctor Doctor
Levels: Lawyer Doctor Non-DL</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Doctor Lawyer Non-DL 
     3      6      3 </code></pre>
</div>
</div>
</section>
<section id="question-11" class="level4">
<h4 class="anchored" data-anchor-id="question-11">Question #11</h4>
<p>Make some interesting plots of the data using ggplot2. Be sure to show different types of figures, multi-variable plots, and use dynamic aesthetics to group data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-11-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-11-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-12" class="level4">
<h4 class="anchored" data-anchor-id="question-12">Question #12</h4>
<p>Use facets to modify your plots.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skeleton_repo_files/figure-html/question-12-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Edmonton, Alberta, is a city in Canada.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>